"""SQLite implementation of ItemRepository."""

from __future__ import annotations

import sqlite3

from app.domain.entities.item import Item
from app.infrastructure.persistence.sqlite.schema import init_schema


class SQLiteItemRepository:
    """ItemRepository implementation using SQLite."""

    def __init__(self, connection: sqlite3.Connection) -> None:
        self._conn = connection
        init_schema(self._conn)

    def list(self) -> list[Item]:
        """Return all items."""
        cursor = self._conn.execute("SELECT id, name FROM items ORDER BY id")
        return [Item(id=row[0], name=row[1]) for row in cursor.fetchall()]

    def add(self, item: Item) -> Item:
        """Persist item; id is generated by SQLite. Returns entity with assigned id."""
        cursor = self._conn.execute(
            "INSERT INTO items (name) VALUES (?)",
            (item.name,),
        )
        self._conn.commit()
        row_id = cursor.lastrowid
        if row_id is None:
            raise RuntimeError("SQLite did not return lastrowid")
        return Item(id=row_id, name=item.name)
